# Directory di default per i caricamenti
upload.path=uploads

# Configurazioni di Spring Multipart
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB


logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.web.access=DEBUG
logging.level.org.springframework.security.authentication=DEBUG
logging.level.org.springframework.security.web.authentication=DEBUG

#PAYPAL
paypal.client.id=AU79gkDiXlpiTSgpybwY5Wut4sxe6DG2ihsaVvIPCV7egBjTRJUYcSSc5_nv27fRCRsVUA-TbCIO4ypC
paypal.client.secret=EMXfEAjxhYPGYBRdQ6UQApTI-tvDKbAB6_fKikJ2e83eHauMZRtLLrzdF0HyfL9AuZZuml4b-Qklbe2z
paypal.mode=sandbox
#STRIPE
stripe.secret.key=sk_test_51QpNkvIX50JfMIoYVkJTzSvG9D5A7UjAqNkvAJ4teqNjBdvT4AkfzosuTAGyl3oP0MGHTRb1puok6wTBIbnn7Af000XyMmsrlE
#STRIPE O PAYPAL
provider.payment.type=paypal