# Directory di default per i caricamenti
upload.path=uploads

# Configurazioni di Spring Multipart
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB


logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.web.access=DEBUG
logging.level.org.springframework.security.authentication=DEBUG
logging.level.org.springframework.security.web.authentication=DEBUG

#PAYPAL
paypal.client.id=TUO_CLIENT_ID
paypal.client.secret=TUA_SECRET_KEY
paypal.mode=sandbox
#STRIPE
stripe.secret.key=TUA_SECRET_KEY
#STRIPE O PAYPAL
provider.payment.type=paypal
